In [10]:
!pip install yfinance # uncomment these to install missing packages if they are not already installed
!pip install pandas

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.6.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.19.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [11]:
import yfinance as yf
import pandas as pd

def get_price(tick,start='2022-10-01',end=None):
    return yf.Ticker(tick).history(start=start,end=end)['Close']

def get_prices(tickers,start='2022-10-01',end=None):
    df=pd.DataFrame()
    for s in tickers:
        df[s]=get_price(s,start,end)
    return df

# Prepare training and testing data sets

In [12]:
feature_stocks=['tsla','meta','goog','amzn','nflx','gbtc','gdx','intc','dal','c']
predict_stock='msft'

# training set
start_date_train='2023-1-01'
end_date_train='2024-6-30'

X_train=get_prices(feature_stocks,start=start_date_train,end=end_date_train)
y_train=get_prices([predict_stock],start=start_date_train,end=end_date_train)

# testing set
start_date_test='2024-11-01'
end_date_test='2024-12-31'
X_test=get_prices(feature_stocks,start=start_date_test,end=end_date_test)
y_test=get_prices([predict_stock],start=start_date_test,end=end_date_test)

In [13]:
X_train

,tsla,meta,goog,amzn,nflx,gbtc,gdx,intc,dal,c
Date,,,,,,,,,,
2023-01-03 00:00:00-05:00,108.099998,123.874702,89.032227,85.820000,29.495001,7.407407,28.634270,25.775145,31.724298,40.836479
2023-01-04 00:00:00-05:00,113.639999,126.486450,88.049622,85.139999,30.941000,7.570009,29.850697,26.691210,33.455952,41.889057
2023-01-05 00:00:00-05:00,110.339996,126.059425,86.124046,83.120003,30.969999,7.633243,29.590033,26.575495,34.273132,41.701740
2023-01-06 00:00:00-05:00,113.059998,129.118088,87.503716,86.080002,31.555000,7.813911,30.468561,27.703701,35.051407,42.201267
2023-01-09 00:00:00-05:00,119.769997,128.571899,88.138947,87.360001,31.517000,8.717254,30.178936,28.262981,35.771309,42.406429
...,...,...,...,...,...,...,...,...,...,...
2024-06-24 00:00:00-04:00,182.580002,496.467255,179.648331,185.570007,66.902000,47.524841,33.608482,30.377298,48.501133,58.291889
2024-06-25 00:00:00-04:00,187.350006,508.100006,184.408112,186.339996,67.240997,49.701897,33.206161,30.546227,47.921871,58.519966
2024-06-26 00:00:00-04:00,196.369995,510.607727,184.199402,193.610001,67.768997,48.897923,33.186535,30.347488,47.303329,58.206364
2024-06-27 00:00:00-04:00,197.419998,517.016235,185.680023,197.850006,68.433998,49.250225,33.588856,30.397173,47.715687,58.491455
2024-06-28 00:00:00-04:00,197.880005,501.751251,182.261749,193.250000,67.487999,48.093948,33.294476,30.774776,46.576794,60.306549

In [14]:
y_train

                                 msft
Date
2023-01-03 00:00:00-05:00  233.985657
2023-01-04 00:00:00-05:00  223.750381
2023-01-05 00:00:00-05:00  217.118866
2023-01-06 00:00:00-05:00  219.677719
2023-01-09 00:00:00-05:00  221.816605
...                               ...
2024-06-24 00:00:00-04:00  442.706116
2024-06-25 00:00:00-04:00  445.949768
2024-06-26 00:00:00-04:00  447.146362
2024-06-27 00:00:00-04:00  447.828705
2024-06-28 00:00:00-04:00  441.994110

[374 rows x 1 columns]

# Convert training and testing data into numpy array

In [15]:
import numpy as np

X_train=np.array(X_train)
y_train=np.array(y_train)
X_test=np.array(X_test)
y_test=np.array(y_test)

# Use linear regression to predict msft stock price from the other stocks' prices

## 1. Append a dummy feature to both X_train and X_test

In [16]:
# Your solution here
# Append dummy feature

X_train = np.hstack([X_train, np.ones((X_train.shape[0], 1))])
X_test  = np.hstack([X_test,  np.ones((X_test.shape[0], 1))])

## 2. Find the best linear regression model based on your training data ($w=(X X')^{-1} X y$)
### Note that you may need to transpose the matrices to make things work

In [17]:
# Your solution here
# Compute w using normal equation

XtX = X_train.T @ X_train
XtX_inv = np.linalg.inv(XtX)
Xt_y = X_train.T @ y_train

w = XtX_inv @ Xt_y

## 3. Report your training and testing error
### How far your prediction from the actual price. Compute the mean square error for both training and testing

In [18]:
# Your solution here
# Predictions
y_train_pred = X_train @ w
y_test_pred  = X_test  @ w
# Mean Squared Error
train_mse = np.mean((y_train_pred - y_train)**2)
test_mse  = np.mean((y_test_pred  - y_test)**2)

print("Training MSE:", train_mse)
print("Testing MSE:", test_mse)

Training MSE: 79.05558908376942
Testing MSE: 7199.865376271677

In [19]:
np.save("linear_weights.npy", w)